date = input("언제 진행된 경기인가요?")
type = input("종목은 무엇인가요?")
stadium = input("경기장은 어디입니까?")
team = input("누구와 누구가 경기를 진행했나요?")
winner = input("이긴 팀은 어디인가요?")
loser = input("진 팀은 어디인가요?")
score = input("스코어는 몇대몇입니까?")

print("=" * 30)
print(f"{date}, {stadium}에서 진행된 {type} 경기의 결과를 알려드립니다.")
print(f"{team} 간의 치열한 공방전이 이어졌었는데요.")
print(f"결국 {winner}가 승리를 쟁취하고 {loser}는 패배하고 말았습니다.")
print(f"{score}인 만큼 {loser}는 정말 아쉬웠겠습니다.")
print("=" * 30)